{
 "title": "Request Overview",
 "tags": [
  "train-track-api",
  "request-overview"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{status=~\"[1-3]..\"}[5m]))) or vector(0)",
     "legendFormat": "good (HTTP < 400)"
    }
   ]
  },
  {
   "title": "Bad Requests by Route (HTTP >= 400)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum by(path) (rate(http_requests_total{status=~\"[4-5]..\"}[5m]))) or vector(0)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Good Requests by Route (HTTP < 400)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum by(path) (rate(http_requests_total{status=~\"[1-3]..\"}[5m]))) or vector(0)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.95, sum by (le, path) (rate(http_request_duration_ms_bucket[5m])))) or vector(0)",
     "legendFormat": "{{path}} p95"
    }
   ]
  },
  {
   "title": "Unique Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(unique_devices_1m) or vector(0)",
     "legendFormat": "1m"
    },
    {
     "expr": "(unique_devices_5m) or vector(0)",
     "legendFormat": "5m"
    },
    {
     "expr": "(unique_devices_1h) or vector(0)",
     "legendFormat": "1h"
    },
    {
     "expr": "(unique_devices_24h) or vector(0)",
     "legendFormat": "24h"
    }
   ]
  }
 ]
}